site_name: Git Comunity Talk



theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust

markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - def_list

plugins:
  - search